# Generated by Django 4.2.6 on 2023-10-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_document_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.TextField(default='# Введіть вміст документа у вигляді Markdown'),
        ),
    ]
