# Generated by Django 4.2.6 on 2023-10-23 15:00

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_alter_document_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='content',
            field=tinymce.models.HTMLField(default='# Введіть вміст документа у вигляді Markdown'),
        ),
    ]
