# Generated by Django 4.2.6 on 2023-10-21 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_total_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='updated',
            new_name='date_updated',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created',
        ),
    ]
