# Generated by Django 4.2.6 on 2023-10-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_updated_user_date_updated_remove_user_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='Not provided', max_length=20),
        ),
    ]
